# Stage 1: Builder
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Stage 2: Runner
FROM node:18-alpine

WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]